# docker-compose.yml

version: '27.3.1'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./spam-classifier
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./spam-classifier:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
